intercom/intercom-php

src/Intercom/Service/config/intercom_public_user.json

fix new_session argument for createUser

fix new_session argument for createUser

---

CHANGES.txt
README.md
src/Intercom/IntercomAbstractClient.php
src/Intercom/IntercomBasicAuthClient.php
src/Intercom/IntercomClientTokenAuthClient.php
src/Intercom/Service/config/intercom_public_contact.json

Fix contact pagination

---

README.md

Changing getNotes to getNotesForUser where appropriate

---

src/Intercom/Model/Iterators/AbstractPageIterator.php

Looks like the the intercom API changed and this abstract iterator was not updated to handle the pagination.

Iterator fix

---

composer.json

fixes https://github.com/intercom/intercom-php/issues/134

require php 5.6

---

src/IntercomClient.php

Otherwise API doesn't allow to interact with notes because of this omission.
Lost 1 hour to realize this..

Bugfix: enable API to interact with notes

---

src/IntercomAdmins.php
src/IntercomBulk.php
src/IntercomClient.php
src/IntercomCompanies.php
src/IntercomConversations.php
src/IntercomCounts.php
src/IntercomEvents.php
src/IntercomLeads.php
src/IntercomMessages.php
src/IntercomNotes.php
src/IntercomTags.php
src/IntercomUsers.php

Added PhpDoc to methods and variables

---

README.md
src/IntercomUsers.php

- Added a new method to IntercomUsers to allow fetching details of a single user by its Intercom id.
- Updated the README.md file to document this new method.
We also need to update the PHP example here: https://developers.intercom.io/reference#view-a-user The method which is used in current example is non-existent,

Get details of a single user

---

README.md

Segments get method called directly from client not tags object

Updated readme segment example

---

README.md

It may be a bit confusing how to add custom attributes to Users and Leads. Added it to the readme to make it easier for new integrations.

added custom_attributes example to users and lead creation

---

README.md
src/IntercomClient.php
src/IntercomConversations.php
src/IntercomUsers.php

Added missing replyToLastConversation() and markConversationAsRead() to IntercomConversations.

add missing conversations calls

---

README.md

Changing names to access tokens and removing API key reference

---

README.md
src/IntercomClient.php
test/IntercomClientTest.php

https://github.com/intercom/intercom-php/pull/164 rebased from master and fixed conflicts

Pagination fixes

---

src/IntercomCompanies.php

missing update method

---

src/IntercomAdmins.php
src/IntercomBulk.php
src/IntercomCompanies.php
src/IntercomConversations.php
src/IntercomCounts.php
src/IntercomEvents.php
src/IntercomLeads.php
src/IntercomMessages.php
src/IntercomNotes.php
src/IntercomSegments.php
src/IntercomTags.php
src/IntercomUsers.php

* follow psr2 standarts
@seferov any addition?

refactoring

---

README.md

I ran into a little difficulty the other day trying to figure out how to send custom attributes similar to what can be done with the JS code. However, because the documentation was not complete it took longer than expect. So, I figure that I'd save someone else the headache and update the readme to reflect this object and its usage.

Update readme to reflect 'custom_attributes' object for Company

---

README.md
src/IntercomConversations.php

fix https://github.com/intercom/intercom-php/issues/169

add options to getConversations

---

src/IntercomSegments.php

Support getting a segment by ID

---

README.md

Adding example to view a segment.

Adding example for viewing segment

---

src/IntercomClient.php
test/IntercomClientTest.php

Allow access to rate limiter headers

---

README.md

Adding readme updates for rate limit PR

---

README.md

As the title of this PR says. 😄

added scroll instructions, fixed formatting

---

composer.json
src/IntercomAdmins.php
src/IntercomBulk.php
src/IntercomClient.php
src/IntercomCompanies.php
src/IntercomConversations.php
src/IntercomCounts.php
src/IntercomEvents.php
src/IntercomLeads.php
src/IntercomMessages.php
src/IntercomNotes.php
src/IntercomSegments.php
src/IntercomTags.php
src/IntercomUsers.php
src/IntercomVisitors.php

Refs https://github.com/intercom/intercom-php/issues/218 :-)

Updated with more PSR2 fixes - refs 

---

README.md

Simple example of how to use the scroll_param to make multiple calls

Adding scroll worked example

---

.circleci/config.yml
circle.yml

Migrating repo to circle 2.0 for https://github.com/intercom/intercom/issues/95392

Migrate to Circle2.0

---

README.md
src/IntercomCompanies.php
test/IntercomCompaniesTest.php

As documented at https://developers.intercom.com/v2.0/reference#view-a-company
Tried to match what the `IntercomUsers` resource was doing (with the `companyPath()` method etc.)

Get a single company by ID

---

README.md
src/IntercomClient.php
src/IntercomCustomers.php
test/IntercomCustomersTest.php

https://developers.intercom.com/intercom-api-reference/v0/reference#customers
Add search feature for customer

Add customer search

---

README.md
src/IntercomCompanies.php
test/IntercomCompaniesTest.php

- Adding the ability to list users of a company
- Fixes: https://github.com/intercom/intercom-php/issues/285
- Adding the appropriate end points

Add support for listing users of a company (Fixes: #285)

---

.circleci/config.yml

Why are you making this change?
We want to add tests for PHP 7.4.
---
Technical details on your change
Adding PHP 7.4 section to `.circleci/config.yml`

Add PHP 7.4 tests.

---

.gitignore

Why are you making this change?
`composer.lock` should not be committed.
---
Technical details on your change
It can safely be added in `.gitignore`

Ignore composer.lock.

---

src/IntercomAdmins.php
src/IntercomBulk.php
src/IntercomCompanies.php
src/IntercomConversations.php
src/IntercomCounts.php
src/IntercomCustomers.php
src/IntercomEvents.php
src/IntercomLeads.php
src/IntercomMessages.php
src/IntercomNotes.php
src/IntercomResource.php
src/IntercomResources.php
src/IntercomSegments.php
src/IntercomTags.php
src/IntercomUsers.php
src/IntercomVisitors.php

Why are you making this change?
We try to introduce thinner classes.
---
Technical details on your change
Introduce an abstract `IntercomResources` that creates the `IntercomClient`.

Abstract to IntercomResources.

---

README.md

Enhancement: Better readability of the docs

---

.gitignore

This is considered a best practice
This should be added to the global gitignore conf of the developer
--

Remove .DS_Store and .idea from .gitignore

---

README.md

Code example can now be copy/pasted
--

Enhancement: Add use statement

---

README.md

Enhancement: Readability and sorted array keys
