src/Intercom/IntercomBasicAuthClient.php, src/Intercom/Service/config/intercom_public_event.json, tests/Intercom/Resources/EventTest.php
fixes https://github.com/intercom/intercom-php/issues/87
cc @dehora
=> Filter empty associative arrays to nulls when passing event metadata

src/IntercomClient.php
Fixed reading of response if it has been already read by something else (like guzzle logging middleware). It happens that ->getContents() don't rewind the Stream. But __toString does: https://github.com/guzzle/psr7/blob/master/src/Stream.php#L90
=> Fixed reading of response if it has been already read

README.md
Edited to use "company_id" instead of "id" as per the [REST API](https://developers.intercom.io/reference) documentation. Added example of how to remove a company from a user.
=> Added steps to remove company from user

src/IntercomClient.php
Fixes #168 in that it has already been fixed, but the docblock doesn't reflect the change. Also means the workarounds now throw errors, so patches should be reversed.
=> FIX docblock to reflect fixed functionality

src/IntercomClient.php, src/IntercomUsers.php
IDs are strings, not integers: https://developers.intercom.com/reference#user-model
Also, `get()` receives the `$query` parameters as an array, not as a string.
=> Use correct PHPdoc types for user IDs

src/IntercomClient.php
fix wrappers/adapters missing notes resource and removed duplicated $segments instanciation line.
I was building an adapter for laravel 5, and noticed the public $notes resource was missing from my wrapper via '__get' because it was not explicitly declared in the Intercom/IntercomClient class definition.
=> fix wrappers/adapters missing notes resource

src/IntercomAdmins.php, test/IntercomAdminsTest.php
We needed to have a quick way to get information about a specific admin, without having to get all the admins and cycle over them to get one name, also preventing us from starting having to use pagination.
=> Add getAdmin function for IntercomAdmins

src/IntercomClient.php
We have Symfony 2.7 with PHP 5.6.31 and "use function" yell some errors. So we have to add this to avoid the error.
=> Avoid 'use function' to ensure compatibility with PHP5.6

src/IntercomAdmins.php, src/IntercomBulk.php, src/IntercomClient.php, src/IntercomCompanies.php, src/IntercomConversations.php, src/IntercomCounts.php, src/IntercomEvents.php, src/IntercomLeads.php, src/IntercomMessages.php, src/IntercomNotes.php, src/IntercomSegments.php, src/IntercomTags.php, src/IntercomUsers.php, src/IntercomVisitors.php, test/IntercomAdminsTest.php, test/IntercomBulkTest.php, test/IntercomClientTest.php, test/IntercomCompaniesTest.php, test/IntercomConversationsTest.php, test/IntercomCountsTest.php, test/IntercomEventsTest.php, test/IntercomLeadsTest.php, test/IntercomMessagesTest.php, test/IntercomNotesTest.php, test/IntercomSegmentsTest.php, test/IntercomTagsTest.php, test/IntercomUsersTest.php, test/IntercomVisitorsTest.php
As surfaced correctly in #218, the library is currently not following the [PSR-2 Coding Style Guidelines](http://www.php-fig.org/psr/psr-2/), which makes it more difficult for developers to contribute with the fear of adding inconsistencies.
This is a not a full attempt to bring the project up to scratch, but I think we should start at least with the consistency in whitespacing, indenting and comments.
I ran `phpcs 3.1.0 stable` with the default configuration options.
To keep track of the changes, these are the summaries and reports through this process:
First `phpcs` scan to both `/src` and `/test`: [src](https://gist.github.com/kmossco/09b1642ef1d3e87033b76a5369c3e190#file-phpcs_src_initial-txt) - [test](https://gist.github.com/kmossco/09b1642ef1d3e87033b76a5369c3e190#file-phpcs_test_ini …
=> Fixed whitespace, indenting and commenting inconsistencies

README.md, src/IntercomLeads.php, test/IntercomLeadsTest.php
With PR #186 we have added the ability to use the Scroll API to list more than 10k users, and this PR adds the same ability for leads.
=> added scroll for leads

src/IntercomUsers.php, test/IntercomUsersTest.php
The changes here include some updating of documentation. It seems that the old delete method was really just archiving the user, based on the official documentation, so I updated the docblock to reflect that.
I also introduced `permanentlyDeleteUser` based on the recommendations in #249 that leverage the `user_delete_requests` endpoint to issue a permanent delete.
=> Introduces the Ability to Permanently Delete a User

src/IntercomClient.php
This `$json` parameter passed as a Guzzle `json` request option is intended to be an `array` as referenced in the calling Intercom endpoint classes.
=> Update docblock type for `$json` parameter

test/IntercomClientTest.php
Some tests aren't indented properly. Even though PSR-2 doesn't set any rule about array indentation or line length limit, I think they look better this way ✨
=> Fix IntercomClientTest indentation

README.md, composer.json, src/IntercomAdmins.php, src/IntercomClient.php, src/IntercomConversations.php
Multiple styling fixes ✨ 
* Fix readme to fit PSR-2 (4 spaces indentation)
* Add `ext-json` in the `composer.json` as it is required for `json_decode`.
* Fix some PHPDocs that were missing stuff, had typos or were missing.
* Remove unused imports
* Add the `$visitors` class variable to `IntercomClient`. It was missing, but due to PHP's magic, it was created on the fly by the constructor.
All credits go to PHPStorm ©️ 
My next step is to check for broken links in the PHPDoc blocks and fix PSR2 in the tests to be able to add linting to the build 😄
=> Styling fixes

.circleci/config.yml, composer.json, test/IntercomAdminsTest.php, test/IntercomBulkTest.php, test/IntercomClientTest.php, test/IntercomCompaniesTest.php, test/IntercomConversationsTest.php, test/IntercomCountsTest.php, test/IntercomEventsTest.php, test/IntercomLeadsTest.php, test/IntercomMessagesTest.php, test/IntercomNotesTest.php, test/IntercomSegmentsTest.php, test/IntercomTagsTest.php, test/IntercomUsersTest.php, test/IntercomVisitorsTest.php
The PSR2 convention is followed in all the source files, so why not enforce PSR2 via CI 😃 
I added the PHP Code Sniffer validation to the CircleCI build. However, the tests were not compliant.
To make them compliant:
* I had to add a namespace to each of them
* After having a namespace, all un-namespaced dependencies (`PHPUnit_Framework_TestCase`, `stdClass` and `DateTimeImmutable`) need to either be imported with an `use` statement or include a backward slash in front of them.
=> Add linting to CI

src/IntercomClient.php
phpstan analyse on my project using intercom-php fails because of the incorrect phpdoc.
`$passwordPart` can be null on `IntercomClient` if access token is used.
https://github.com/intercom/intercom-php#clients
=> phpdoc typehint fix

.circleci/config.yml, README.md, composer.json, phpunit.xml, test/IntercomAdminsTest.php, test/IntercomBulkTest.php, test/IntercomClientTest.php, test/IntercomCompaniesTest.php, test/IntercomConversationsTest.php, test/IntercomCountsTest.php, test/IntercomEventsTest.php, test/IntercomLeadsTest.php, test/IntercomMessagesTest.php, test/IntercomNotesTest.php, test/IntercomSegmentsTest.php, test/IntercomTagsTest.php, test/IntercomUsersTest.php, test/IntercomVisitorsTest.php
[PHP 5.6 and 7.0 are no longer supported](http://php.net/supported-versions.php). We should only support active versions (7.1, 7.2 and 7.3 at the time of writing)
This PR drops the support for PHP < 7.1 and splits the circle tests to ensure it works in all of those versions.
PHPUnit 4 is both unsupported and not compatible with PHP >=7.2. [PHPUnit 7 is compatible with php 7.1 to 7.3](https://phpunit.de/supported-versions.html), so I'm upgrading to that version.
=> Upgrade to PHP 7.1+

README.md, composer.json, src/IntercomAdmins.php, src/IntercomBulk.php, src/IntercomClient.php, src/IntercomCompanies.php, src/IntercomConversations.php, src/IntercomCounts.php, src/IntercomEvents.php, src/IntercomLeads.php, src/IntercomMessages.php, src/IntercomNotes.php, src/IntercomSegments.php, src/IntercomTags.php, src/IntercomUsers.php, src/IntercomVisitors.php, test/IntercomClientTest.php
As raised in https://github.com/intercom/intercom-php/issues/255, the restriction to use Guzzle6 is a blocker for some users, especially when using other versions of the library.
[HTTPPlug](http://httplug.io/) allows us to abstract our HTTP Client implementation, and allow the SDK users to decide which client to use. It also provides enough tooling to discover already existing clients, so unless there's an especial need, this SDK will work out of the box. If a more specific implementation is required, you can still pass your custom client using the `setClient` method.
1. Update your composer.json file, so you set the version `dev-ga/http-plug`.
1. See the upgrade notes at the bottom of this PR
✅ This PR has been tested and it is ready to review
Draft release notes:
> This version …
=> Abstract the HTTP client using HTTPPlug

src/IntercomClient.php
not up-to-date properties name
=> Fix IntercomClient incorrectly named variables

README.md
As raised in https://github.com/intercom/intercom-php/issues/273, this repository is not clear on how to use the API Versioning.
I have added a readme section that explains how to use different API versions with this library.
=> Add versioning information to README

src/IntercomAdmins.php, src/IntercomBulk.php, src/IntercomClient.php, src/IntercomCompanies.php, src/IntercomConversations.php, src/IntercomCounts.php, src/IntercomEvents.php, src/IntercomLeads.php, src/IntercomMessages.php, src/IntercomNotes.php, src/IntercomSegments.php, src/IntercomTags.php, src/IntercomUsers.php, src/IntercomVisitors.php
To make [PhpStan](https://github.com/phpstan/phpstan) not complain about unknown class `Intercom\stdClass`.
Example:
```
Access to property $id on an unknown class Intercom\stdClass.
```
I've chosen just adding `\` but if you would prefer `use stdClass;` instead I can update this PR.
=> Make return phpDoc of stdClass fully qualified

composer.json
Breaks compatibility with other packages requiring `php-http/client-common`
And bump version to 4.0.3 please ;)
Fixes https://github.com/intercom/intercom-php/issues/279
=> Added support of version 2+ of php-http/client-common

src/IntercomAdmins.php, src/IntercomBulk.php, src/IntercomClient.php, src/IntercomCompanies.php, src/IntercomConversations.php, src/IntercomCounts.php, src/IntercomCustomers.php, src/IntercomEvents.php, src/IntercomLeads.php, src/IntercomMessages.php, src/IntercomNotes.php, src/IntercomSegments.php, src/IntercomTags.php, src/IntercomUsers.php, src/IntercomVisitors.php
=> Type hinting

.gitattributes
By ignoring the tests and build information, people who install the library (typically via composer) will have fewer files to deal with that they don't need to use the library. People developing against it will still have access to them via a normal checkout.
Add a .gitattributes file to exclude certain paths from export.
=> Add .gitattributes to shrink installs

README.md
Adding missing tag above visitors section so it's not inside the codeblock.
=> Fix missing closing code tag in README

.github/ISSUE_TEMPLATE.md
It can be of tremendous help to have the Intercom API Version in the incoming issues
Add it to the template
=> Add API Version to GitHub template

.circleci/config.yml, .codeclimate.yml, .editorconfig, .gitattributes, .gitignore, composer.json, phpunit.xml.dist
Why are you making this change?
We want to add many small improvements to this project.
---
Technical details on your change
See comments in code for the detailed changes
=> Many improvements.

README.md, src/IntercomClient.php, src/IntercomTeams.php, test/IntercomTeamsTest.php
- Teams are not yet supported: Issue #300 
- Added a new `IntercomTeams` resource, with two endpoints: `getTeams` and `getTeam`
- Added tests
- Updated readme file
=> Add support for teams

README.md, src/IntercomClient.php
Closes https://github.com/intercom/intercom-php/issues/293
We want to be more transparent on the README about which resources are available in which API versions.
Adding notes to the supported API versions. Also updating the user-agent, which was accidentally deleted some time ago.
=> Update readme with API versions

README.md, src/IntercomContacts.php, test/IntercomContactsTest.php
"update" should follow the same pattern as other methods like deleteContact and getContact that require "id" based on the API documentation. https://developers.intercom.com/intercom-api-reference/reference#update-contact
Because the update method is currently broken for Contacts.
Adds id as a required param.
=> fixing broken Contacts update method

src/IntercomClient.php
You'll probably want better tests here....
Fix a bug
nextSearchPage ends up calling handleResponse twice.
=> Fix bug where handleResponse() is called twice

.circleci/config.yml, composer.json
As that config could be broken/invalid
Using `composer validate`
=> Validate Composer configuration in CI

.gitignore, composer.json, tests/IntercomClientTest.php, tests/TestCase.php
Provide compatibility with PHP 8.0 (released yesterday).
Guzzle 6 supports PHP <= 7.4 and Guzzle 7 supports PHP 7.2 - 8.0.
The packaging gymnastics to support Guzzle 6 + 7 is only needed if PHP 7.1 support is still desired (https://www.php.net/supported-versions.php). If not, this PR can be simplified a lot, using only Guzzle 7 for the test suite and supporting PHP >= 7.2.
=> Provide PHP 8.0 compatibility

src/IntercomClient.php
Solves the same issue as #318 but for the nextCursorPage method.
Fixing a bug.
Remove the duplicate handleResponse() call. `get()` already calls it.
=> Fix double handleResponse() bug for nextCursorPage

tests/IntercomSegmentsTest.php
Fix testing class name to be same as PHP file name.
=> Fix testing class name to be same as PHP file name

README.md, src/IntercomConversations.php, tests/IntercomConversationsTest.php
- Creating conversation API is not covered
- https://developers.intercom.com/intercom-api-reference/reference#create-a-conversation
- Add `create` method to `IntercomConversations` class
- Add test
- Update README
=> Add create conversation method

composer.json, src/IntercomClient.php, tests/IntercomClientTest.php
Using `HttpClient`, `HttpClientDiscovery`, `MessageFactoryDiscovery`, and `UriFactory` is deprecated.
Used new Psr17/Psr18 interface instead of the deprecated once and changed the request behaviour.
=> HTTP: add support for PSR17/PSR18 and drop usage of deprecated client discovery
